# Generated by Django 4.2.1 on 2023-06-07 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='An',
            fields=[
                ('An_id', models.CharField(max_length=19, primary_key=True, serialize=False, verbose_name='公告id  An+14日期+random(3)')),
                ('An_text', models.TextField(verbose_name='公告內容')),
                ('An_dateON', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('An_dateOFF', models.IntegerField(null=True, verbose_name='展示狀態')),
            ],
        ),
        migrations.CreateModel(
            name='APP_Cus',
            fields=[
                ('Cus_id', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='客戶編號 c+14日期時間+random(3)')),
                ('Cus_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創立時間')),
                ('Cus_user', models.CharField(max_length=512, unique=True, verbose_name='客戶帳號')),
                ('Cus_pwd', models.CharField(max_length=32, verbose_name='客戶密碼')),
                ('Voucher_count', models.IntegerField(verbose_name='按摩卷擁有數量')),
                ('Cus_status', models.IntegerField(verbose_name='帳號停用')),
                ('Referrer_id', models.CharField(max_length=18, null=True, verbose_name='引薦人')),
                ('Cus_Name', models.CharField(default='user1', max_length=512, null=True, verbose_name='APP客戶姓名 (default後面數字逐漸增加)')),
            ],
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('Chair_id', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='編號 C001')),
                ('Chair_cost', models.IntegerField(verbose_name='租金費用')),
                ('Chair_frequency', models.IntegerField(default=0, null=True, verbose_name='被騎乘次數')),
                ('Chair_state', models.IntegerField(null=True, verbose_name='狀態(維修0/正常1/爆炸2/正在使用3)')),
                ('Chair_years', models.IntegerField(null=True, verbose_name='使用年限')),
            ],
        ),
        migrations.CreateModel(
            name='Cou',
            fields=[
                ('Cou_ID', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='按摩券編號/Cou00001')),
                ('Cou_DATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='購入日期')),
                ('Cou_STATUS', models.IntegerField(verbose_name='啟用狀態')),
                ('Cou_COST', models.IntegerField(verbose_name='售價')),
            ],
        ),
        migrations.CreateModel(
            name='Cp',
            fields=[
                ('Cp_NUM', models.IntegerField(verbose_name='剩餘數量')),
                ('Cp_ID', models.CharField(max_length=19, primary_key=True, serialize=False, verbose_name='進貨批號 CP+14日期時間+random(3)')),
                ('Cp_DATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='進貨時間')),
            ],
        ),
        migrations.CreateModel(
            name='demand',
            fields=[
                ('demand_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='需求類型ID(n+0001)')),
                ('demand_text', models.TextField(verbose_name='需求名稱(EX主要按摩部位需求 顏色偏好 客戶職業)')),
            ],
        ),
        migrations.CreateModel(
            name='FALSE',
            fields=[
                ('FALSE_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='失敗因素編號(fa+001)')),
                ('FALSE_TYPE', models.CharField(max_length=512, unique=True, verbose_name='失敗因素類別')),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('Marketing_id', models.CharField(max_length=19, primary_key=True, serialize=False, verbose_name='編號(M+14date+0001)')),
                ('Marketing_reserve', models.DateTimeField(null=True, verbose_name='預約下次來店日期')),
                ('Marketing_discount', models.TextField(null=True, verbose_name='推薦的優惠')),
                ('Marketing_remark', models.TextField(null=True, verbose_name='備註')),
                ('Marketing_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.CharField(max_length=22, primary_key=True, serialize=False, verbose_name='訂單編號 order+14+random(3)')),
                ('Cus_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.app_cus')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='產品id P+001')),
                ('product_name', models.CharField(max_length=512, verbose_name='產品名')),
                ('product_price', models.IntegerField(verbose_name='單價')),
                ('product_status', models.IntegerField(default=1, verbose_name='上/下架 1/0')),
                ('product_discript', models.TextField(max_length=512, verbose_name='商品說明')),
                ('product_type', models.CharField(max_length=32, verbose_name='需求用途')),
                ('product_size', models.FloatField(verbose_name='產品尺寸')),
            ],
        ),
        migrations.CreateModel(
            name='Sp',
            fields=[
                ('Sp_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='業務員ID(PK)/Sp001')),
                ('Sp_bonus', models.IntegerField(null=True, verbose_name='本月獎金')),
                ('Sp_formula', models.IntegerField(verbose_name='績效公式')),
                ('Sp_salary', models.IntegerField(verbose_name='業務員薪水')),
                ('Sp_address', models.CharField(max_length=512, verbose_name='住家地址')),
                ('Sp_tel', models.CharField(max_length=12, verbose_name='電話號碼')),
                ('Sp_name', models.CharField(max_length=15, verbose_name='業務員姓名')),
                ('Sp_lv', models.CharField(max_length=10, verbose_name='業務員職位')),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('store_id', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='店家id S+001')),
                ('store_address', models.CharField(max_length=512, verbose_name='地址')),
                ('store_createtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創立時間')),
                ('store_member', models.IntegerField(verbose_name='員工人數')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('Ab_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='graph.sp')),
                ('Ab_DATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='排班日期')),
                ('Ab_STIME', models.DateTimeField(verbose_name='排班開始時間')),
                ('Ab_ETIME', models.DateTimeField(verbose_name='排班結束時間')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('Trade_id', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='交易編號 T+14日期時間+random(3)')),
                ('Voucher_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='發放時間')),
                ('Voucher_status', models.IntegerField(verbose_name='使用狀況')),
                ('Cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.app_cus')),
                ('Voucher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.cou')),
                ('Voucher_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.sp')),
            ],
        ),
        migrations.CreateModel(
            name='storeboard',
            fields=[
                ('storeboard_id', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='店家儀錶板流水號 SB+14時間+random(2)')),
                ('storeboard_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='店家儀錶板成立時間')),
                ('store_username', models.CharField(max_length=512, unique=True, verbose_name='店家帳號(供自由發揮)')),
                ('store_pwd', models.CharField(max_length=32, verbose_name='店家密碼')),
                ('store_status', models.IntegerField(null=True, verbose_name='店家帳號狀況')),
                ('store_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.store')),
            ],
        ),
        migrations.AddField(
            model_name='sp',
            name='Sp_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.store'),
        ),
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('Bref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r2', to='graph.app_cus')),
                ('Referrer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r1', to='graph.app_cus')),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.app_cus')),
                ('Marketing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.marketing')),
            ],
        ),
        migrations.CreateModel(
            name='order_detailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='下單時間')),
                ('totalprice', models.IntegerField(verbose_name='訂單總額')),
                ('order_addr', models.CharField(max_length=512, verbose_name='運送地址')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Sp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.sp'),
        ),
        migrations.CreateModel(
            name='need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=4, verbose_name='類型種類ID(Ty+001)')),
                ('type_name', models.TextField(unique=True, verbose_name='類型種類選項')),
                ('demand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.demand')),
            ],
        ),
        migrations.AddField(
            model_name='marketing',
            name='Marketing_clerk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.sp'),
        ),
        migrations.AddField(
            model_name='marketing',
            name='Marketing_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.app_cus'),
        ),
        migrations.CreateModel(
            name='manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='回饋日期')),
                ('manage_deal', models.BooleanField(verbose_name='成交與否')),
                ('manage_detail', models.TextField(verbose_name='失敗原因詳述')),
                ('manage_stage', models.IntegerField(verbose_name='聯絡次數')),
                ('Cus_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='graph.app_cus')),
                ('Sp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.sp')),
                ('manage_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='graph.false')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.store')),
            ],
        ),
        migrations.CreateModel(
            name='Cus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cus_FamilyNum', models.IntegerField(null=True, verbose_name='家庭成員數量')),
                ('Cus_eld', models.IntegerField(null=True, verbose_name='長者有無')),
                ('Chair_status', models.IntegerField(null=True, verbose_name='家中是否有按摩椅')),
                ('Chair_floor', models.IntegerField(null=True, verbose_name='客戶消費預算下限')),
                ('Chair_ceiling', models.IntegerField(null=True, verbose_name='客戶消費預算上限')),
                ('Chair_position', models.CharField(max_length=50, null=True, verbose_name='主要按摩部位需求 (不要想歪')),
                ('Chair_color', models.CharField(max_length=50, null=True, verbose_name='顏色偏好')),
                ('Cus_PastItem', models.CharField(max_length=520, null=True, verbose_name='過去消費過的品牌產品')),
                ('Chair_power', models.IntegerField(null=True, verbose_name='按摩模式力道偏好 (1~10 弱到強)')),
                ('Cus_job', models.CharField(max_length=50, null=True, verbose_name='客戶職業')),
                ('Cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.app_cus')),
                ('product_past', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cu',
            fields=[
                ('Cu_exID', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='編號(U+date+001)')),
                ('Cu_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('Cu_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='graph.chair')),
                ('Cu_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.app_cus')),
            ],
        ),
        migrations.AddField(
            model_name='cou',
            name='Cp_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.cp'),
        ),
        migrations.CreateModel(
            name='cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_cost', models.IntegerField(verbose_name='實體店面營運成本')),
                ('rent_cost', models.IntegerField(verbose_name='按摩椅租地成本')),
                ('voucher_cost', models.IntegerField(verbose_name='按摩卷申請成本')),
                ('upper_cost', models.IntegerField(verbose_name='試坐按摩椅租金成本')),
                ('other_cost', models.IntegerField(verbose_name='其他支出')),
                ('cost_month', models.DateTimeField(default=django.utils.timezone.now, verbose_name='成本月份')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.store')),
            ],
        ),
        migrations.AddField(
            model_name='chair',
            name='Chair_pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.product'),
        ),
        migrations.AddField(
            model_name='chair',
            name='Chair_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.store'),
        ),
        migrations.CreateModel(
            name='Ab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ab_ON', models.IntegerField(verbose_name='打卡上班')),
                ('Ab_OFF', models.IntegerField(verbose_name='打卡上班')),
                ('Ab_DATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('Ab_REASON', models.TextField(verbose_name='請假理由')),
                ('Ab_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.app_cus')),
            ],
        ),
    ]
