# Generated by Django 4.2.1 on 2023-06-09 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='arrange',
            fields=[
                ('Ab_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='graph.sp')),
                ('Ab_DATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='排班日期')),
                ('Ab_STIME', models.DateTimeField(verbose_name='排班開始時間')),
                ('Ab_ETIME', models.DateTimeField(verbose_name='排班結束時間')),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Ab_DATE',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Ab_ETIME',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Ab_ID',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Ab_STIME',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedbackCu_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='graph.chair'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='回饋日期'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_id',
            field=models.CharField(default=0, max_length=18, primary_key=True, serialize=False, verbose_name='回饋表id F+14日期+random(3)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(default=0, verbose_name='回饋內容'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedcus_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='graph.app_cus'),
        ),
    ]
