# Generated by Django 4.1.5 on 2023-06-10 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_arrange_remove_feedback_ab_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrange',
            name='Ab_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.sp'),
        ),
        migrations.AlterField(
            model_name='manage',
            name='manage_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.false'),
        ),
        migrations.AlterField(
            model_name='order_detailed',
            name='order_addr',
            field=models.TextField(verbose_name='運送地址'),
        ),
    ]
