# Generated by Django 4.1.5 on 2023-06-10 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_arrange_ab_id_alter_manage_manage_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrange',
            name='Ab_ID',
        ),
        migrations.AddField(
            model_name='arrange',
            name='Ab_Sp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='graph.sp'),
        ),
        migrations.AddField(
            model_name='arrange',
            name='Ab_id',
            field=models.CharField(default=1, max_length=5, primary_key=True, serialize=False, verbose_name='排班(ar+001)'),
        ),
    ]
