# Generated by Django 4.1.5 on 2023-06-10 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_remove_arrange_ab_id_arrange_ab_sp_arrange_ab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='manage_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.false'),
        ),
        migrations.AlterField(
            model_name='manage',
            name='manage_detail',
            field=models.TextField(null=True, verbose_name='失敗原因詳述'),
        ),
    ]
