# Generated by Django 4.1.5 on 2023-06-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_alter_ab_ab_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cus',
            name='id',
        ),
        migrations.AlterField(
            model_name='cus',
            name='Cus_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='graph.app_cus'),
        ),
    ]
