# Generated by Django 4.1.5 on 2023-06-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0008_alter_arrange_ab_sp_alter_arrange_ab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrange',
            name='Ab_Sp',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, to='graph.sp'),
        ),
    ]
