# Generated by Django 4.1.5 on 2023-06-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_alter_arrange_ab_sp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cus',
            name='Chair_ceiling',
            field=models.IntegerField(blank=True, null=True, verbose_name='客戶消費預算上限'),
        ),
        migrations.AlterField(
            model_name='cus',
            name='Chair_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='顏色偏好'),
        ),
        migrations.AlterField(
            model_name='cus',
            name='Chair_floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='客戶消費預算下限'),
        ),
        migrations.AlterField(
            model_name='cus',
            name='Chair_position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主要按摩部位需求 (不要想歪'),
        ),
        migrations.AlterField(
            model_name='cus',
            name='Chair_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='按摩模式力道偏好 (1~10 弱到強)'),
        ),
        migrations.AlterField(
            model_name='cus',
            name='Chair_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='家中是否有按摩椅'),
        ),
        migrations.AlterField(
            model_name='cus',
            name='Cus_FamilyNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='家庭成員數量'),
        ),
        migrations.AlterField(
            model_name='cus',
            name='Cus_PastItem',
            field=models.CharField(blank=True, max_length=520, null=True, verbose_name='過去消費過的品牌產品'),
        ),
        migrations.AlterField(
            model_name='cus',
            name='Cus_eld',
            field=models.IntegerField(blank=True, null=True, verbose_name='長者有無'),
        ),
        migrations.AlterField(
            model_name='cus',
            name='Cus_job',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='客戶職業'),
        ),
        migrations.AlterField(
            model_name='cus',
            name='product_past',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.product'),
        ),
    ]
