# Generated by Django 4.1.5 on 2023-06-11 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0010_alter_cus_chair_ceiling_alter_cus_chair_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='an',
            name='An_dateOFF',
            field=models.IntegerField(blank=True, null=True, verbose_name='展示狀態'),
        ),
        migrations.AlterField(
            model_name='app_cus',
            name='Cus_Name',
            field=models.CharField(blank=True, default='user1', max_length=512, null=True, verbose_name='APP客戶姓名 (default後面數字逐漸增加)'),
        ),
        migrations.AlterField(
            model_name='app_cus',
            name='Referrer_id',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='引薦人'),
        ),
        migrations.AlterField(
            model_name='chair',
            name='Chair_state',
            field=models.IntegerField(blank=True, null=True, verbose_name='狀態(維修0/正常1/爆炸2/正在使用3)'),
        ),
        migrations.AlterField(
            model_name='chair',
            name='Chair_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='使用年限'),
        ),
        migrations.AlterField(
            model_name='cou',
            name='Cp_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.cp'),
        ),
        migrations.AlterField(
            model_name='manage',
            name='manage_detail',
            field=models.TextField(blank=True, null=True, verbose_name='失敗原因詳述'),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='Marketing_discount',
            field=models.TextField(blank=True, null=True, verbose_name='推薦的優惠'),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='Marketing_remark',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='Marketing_reserve',
            field=models.DateTimeField(blank=True, null=True, verbose_name='預約下次來店日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Cus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.app_cus'),
        ),
        migrations.AlterField(
            model_name='order_detailed',
            name='order_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='下單時間'),
        ),
        migrations.AlterField(
            model_name='sp',
            name='Sp_bonus',
            field=models.IntegerField(blank=True, null=True, verbose_name='本月獎金'),
        ),
        migrations.AlterField(
            model_name='storeboard',
            name='store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.store'),
        ),
        migrations.AlterField(
            model_name='storeboard',
            name='store_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='店家帳號狀況'),
        ),
    ]
