# Generated by Django 4.1.5 on 2023-06-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0012_alter_ab_ab_id_alter_arrange_ab_sp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ab',
            name='Ab_OFF',
            field=models.IntegerField(verbose_name='打卡下班'),
        ),
    ]
