# Generated by Django 4.1.5 on 2023-06-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0013_alter_ab_ab_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='Voucher_type',
            field=models.CharField(default=0, max_length=2, verbose_name='銷售贈予狀態'),
        ),
    ]
