# Generated by Django 4.1.5 on 2023-06-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0014_trade_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage',
            name='manage_frequency',
            field=models.IntegerField(default=0, verbose_name='聯絡次數'),
        ),
        migrations.AlterField(
            model_name='manage',
            name='manage_stage',
            field=models.IntegerField(verbose_name='展示狀態'),
        ),
    ]
