from django.contrib import admin

# Register your models here.

from graph.models import *
admin.site.register(store)
admin.site.register(Sp)
admin.site.register(product)
admin.site.register(APP_Cus)
admin.site.register(Cus)
admin.site.register(storeboard)
admin.site.register(order)
admin.site.register(order_detailed)
admin.site.register(Marketing)
admin.site.register(record)
admin.site.register(Chair)
admin.site.register(Cu)
admin.site.register(Cp)
admin.site.register(Cou)
admin.site.register(Trade)
admin.site.register(Referrer)
admin.site.register(Ab)
admin.site.register(cost)
admin.site.register(arrange)
admin.site.register(An)
admin.site.register(demand)
admin.site.register(need)
admin.site.register(feedback)
admin.site.register(FALSE)
admin.site.register(manage)